name: Feature request
description: Suggest an idea or feature update this project.
title: "[Feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request and provide feedback!
  - type: textarea
    id: feature
    attributes:
      label: What is your feature request?
      description: Provide clear details about the feature you want to see added to Evergreen.
      placeholder: "Describe details about the feature you'd like to see that could be added to Evergreen."
    validations:
      required: true
  - type: checkboxes
    id: version
    attributes:
      label: Have you tested against the current version?
      description: "Please confirm that you've tested the current version before making this feature request."
      options:
        - label: "Yes, I've updated Evergreen and tested against the current version."
  - type: checkboxes
    id: documentation
    attributes:
      label: Have you reviewed the documentation?
      description: "Please confirm that you've reviewed the documentation before making this feature request."
      options:
        - label: "Documentation at: https://stealthpuppy.com/evergreen/"
